valuesFilePath: ./values.yml
resources:
  - name: {{ .Values.namePrefix }}_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repo.path }}
      gitProvider: {{ .Values.repo.gitIntegration }}
      branches:
        include: {{ .Values.repo.branchPattern | default "main" }}


pipelines:
  - name: {{ .Values.namePrefix }}_go_ci
    steps:
      - name: build
        type: Bash
        configuration:
          affinityGroup: {{ .Values.namePrefix }}_go_binary_ci
          environmentVariables:
            JFROG_CLI_BUILD_NAME: {{ .Values.namePrefix }}_go_binary_ci
            JFROG_CLI_BUILD_NUMBER: ${run_id}
        execution:
          onExecute:
            - echo Hello pipleins
      - name: publish
        type: Bash
        configuration:
          inputSteps:
          - name: build 
        execution:
          onExecute:
            - echo Publish!!!

