valuesFilePath: ./values.yml
resources:
  - name: {{ .Values.namePrefix }}_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repo.path }}
      gitProvider: {{ .Values.repo.gitIntegration }}
      branches:
        include: {{ .Values.repo.branchPattern | default "main" }}

{{ if .Values.publishBuild }}
  {{ if .Values.goConfig.binaryTargetRepository }}
  - name: {{ .Values.namePrefix }}_binary_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}

  - name: {{ .Values.namePrefix }}_binary_spec
    type: FileSpec
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}
      pattern: '{{ .Values.binaryBuildSpecPattern | default "*" }}'
      buildName: ${JFROG_CLI_BUILD_NAME}
      buildNumber: ${JFROG_CLI_BUILD_NUMBER}
  {{ end }}

  {{ if .Values.goConfig.moduleTargetRepository }}
  - name: {{ .Values.namePrefix }}_module_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}

  - name: {{ .Values.namePrefix }}_module_spec
    type: FileSpec
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}
      pattern: '{{ .Values.moduleBuildSpecPattern | default "*" }}'
      buildName: ${JFROG_CLI_BUILD_NAME}
      buildNumber: ${JFROG_CLI_BUILD_NUMBER}
  {{ end }}

{{ end }}


pipelines:
  - name: {{ .Values.namePrefix }}_go_ci
    steps:
      - name: build
        type: Bash
        configuration:
          affinityGroup: {{ .Values.namePrefix }}_go_binary_ci
          environmentVariables:
            JFROG_CLI_BUILD_NAME: {{ .Values.namePrefix }}_go_binary_ci
            JFROG_CLI_BUILD_NUMBER: ${run_id}
        execution:
          onExecute:
            - echo Hello pipleins

      - name: publish
        type: Bash
        execution:
          onExecute:
            - echo Publish!!!

